# Generated by Django 3.1.7 on 2021-03-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateDemographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_highschool_grad_rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('black_highschool_grad_rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('white_college_grad_rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('black_college_grad_rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('black_median_income', models.PositiveIntegerField()),
                ('white_median_income', models.PositiveIntegerField()),
                ('black_population_percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('black_population_raw_amount', models.PositiveIntegerField()),
                ('white_population_percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('white_population_raw_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
