# Generated by Django 3.1.7 on 2021-03-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210310_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='statedemographic',
            name='state',
            field=models.CharField(default='NY', max_length=30),
            preserve_default=False,
        ),
    ]
